// Testimonials data
export const testimonials = [
  {
    id: 1,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Un séjour magique et dépaysant, riche en nouvelles expériences et en belles découvertes culturelles. Entre aventures inoubliables, traditions locales et rencontres formidables, ce voyage restera un excellent souvenir.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 2,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Un city trip inoubliable, parfaitement orchestré, à la découverte d'un pays aussi riche que méconnu. Un programme de grande qualité, porté par une organisation bienveillante, des rencontres marquantes et des moments de partage remplis de rires et de souvenirs forts.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 3,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Un dépaysement total et une expérience unique, rythmée par des activités exceptionnelles et des paysages à couper le souffle. Des rencontres humaines incroyables et des moments magiques qui laissent déjà un doux sentiment de nostalgie.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 4,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Une expérience incroyable, portée par une organisation sans faille et un service impeccable du début à la fin. Des paysages grandioses et une aventure inoubliable, digne d'un véritable rêve devenu réalité.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 5,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Un dépaysement total et une immersion fascinante dans une autre culture. Une destination superbe, ponctuée de lieux insolites et d'activités d'exception, pour des souvenirs absolument inoubliables.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 6,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Un séjour parfaitement rythmé, mêlant découvertes culturelles, paysages spectaculaires et art de vivre local. Une immersion authentique et vibrante, riche en émotions, en partages et en souvenirs marquants.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 7,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Une destination surprenante, pleine de richesses naturelles et culturelles. Une organisation parfaite et des accompagnateurs toujours disponibles et attentif ont rendu ce voyage unique et mémorable.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 8,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Une ambiance exceptionnelle portée par des accompagnatrices et des guides au top. Une destination spectaculaire, vécue dans une atmosphère conviviale et dynamique, pour un voyage mémorable.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 9,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Des paysages sublimes, des visites incontournables et de belles surprises tout au long du séjour. Un premier voyage inoubliable, riche en échanges et en émotions, qui restera gravé longtemps.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 10,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Ce séjour nous a permis de découvrir un pays souvent méconnu et pourtant fascinant. Nous sommes ravis d'avoir vécu des expériences uniques et inoubliables, que nous n'aurions peut-être jamais eu l'occasion de vivre autrement.",
    photo: "/images/testimonial.jpg",
  },
  {
    id: 11,
    name: "Client Amedida",
    role: "Voyageur",
    text: "Un séjour unique et mémorable, avec une organisation impeccable et des activités inoubliables. Une accompagnatrice formidable a rendu l'expérience encore plus exceptionnelle.",
    photo: "/images/testimonial.jpg",
  },
];
